### ISSUE TITLE
Performance Very Poor Compared to Unix Diff Tool

### ISSUE THREAD

**Issue by DaGeRe** [java-diff-utils/java-diff-utils#148]
**Describe the bug**
I would expect an implementation of the Myers diff algorithm to behave (at least asymptotically) equal. Unfortunately, this is not the case for this implementation: Starting with ~100k lines that are compared, the time consumption growth heavily (at least more than linear).

You can see this in the following graph:

![grafik](https://user-images.githubusercontent.com/4358467/173233081-4b4c4941-e0c6-4338-a604-270475fcd04f.png)

**To Reproduce**
1. Use https://github.com/DaGeRe/diff-benchmark (which contains [414ae6.zip](https://github.com/DaGeRe/diff-benchmark/blob/main/414ae6.zip) and [afdedc.zip](https://github.com/DaGeRe/diff-benchmark/blob/main/afdedc.zip) which contain data that can be compared)
2. Run `[runJavaDiff.sh](https://github.com/DaGeRe/diff-benchmark/blob/main/java-difflib-benchmark/runJavaDiff.sh)` and [runBashDiff.sh](https://github.com/DaGeRe/diff-benchmark/blob/main/unix/runBashDiff.sh) to obtain the measurement values. 
3. Copy the measurement data and execute [plot.plt](https://github.com/DaGeRe/diff-benchmark/blob/main/results/plot.plt) to obtain the graph.

**Expected behavior**
The duration of the diff execution should grow linear with count of analyzed lines.

**System**
 - Java version 1.8
 - Version 4.11

**Comment by wumpz** [comment]
Did you use the new Meyer Alg implementation (#134)? Since the unix tools using the proposed variant of Meyers algorithm with linear space and a significant performance gain, I am surprised that DiffTools perform not worse. Look into the the issue and try the new implementation. This one is not yet the default algorithm, that DiffUtils use.

Another point is, but that is my taste, that the original algorithm does provide more natural patches and suits better for inline comparision.

**Comment by wumpz** [comment]
Any more tests here?
