### ISSUE TITLE
The output is wrong

### ISSUE THREAD

**Issue by Lvbuqing** [java-diff-utils/java-diff-utils#160]
jdk1.8
os：win10
<groupId>io.github.java-diff-utils</groupId>
<artifactId>java-diff-utils</artifactId>
<version>4.12</version>

![image](https://user-images.githubusercontent.com/32841009/210694936-791f313f-bea5-43fe-aeb6-f765faafcbd2.png)

The correct output is:
first line：The correct one should be: |aaaa~b~|aaaa**c**|                 Not at all:|~aaaab~|**aaaac**|
Third line: The correct one should be: |ttt~t~ttt|ttt**r**ttt|			   Not at all:|~ttttttt~|**tttrttt**|
![image](https://user-images.githubusercontent.com/32841009/210695894-a3f76691-541b-4502-9d4e-39e7b411ddc5.png)

**Comment by wumpz** [comment]
You are using **inline diff by word**, aaaab is a word. You have to put an own splitter into it to achieve your result. 

You have to use something like this. However now the complete input is treated single characters and you will get some unexpected results.

```java
List<DiffRow> rows = DiffRowGenerator.create()
                .showInlineDiffs(true)
                //.inlineDiffByWord(true)
                .inlineDiffBySplitter(DiffRowGenerator.SPLITTER_BY_CHARACTER)
                .decompressDeltas(true)
                .oldTag(f -> "~")
                .newTag(f -> "**")
                .build()
                .generateDiffRows(
                        Arrays.asList("aaaab", "aaaaaa", "ttttttt"), 
                        Arrays.asList("aaaac", "bbbbbb", "tttrttt"));

        System.out.println("|original|new|");
        System.out.println("|--------|---|");
        for (DiffRow row : rows) {
            System.out.println("|" + row.getOldLine() + "|" + row.getNewLine() + "|");
        }
```

|original|new|
|--------|---|
|aaaab|aaaa**c**|
|~aaaaaa~|b**bbbbb**|
|tttttt~t~|ttt**r**ttt|

For instance the first line is **aaaab\n**. So **c** inerts in fact here **c\n** , thats why the last b is suddenly in the second line.

JavaDiffUtils are having problems here due to linefeed handling. You could expect better results, when you only insert line by line.
