### ISSUE TITLE
Feature request: Table Diff

### ISSUE THREAD

**Issue by wise-coders** [java-diff-utils/java-diff-utils#166]
Is it possible to extend the library with support for comparing two tables?
Like comparing the results of two result Sets.
A comparison between String[][] <--> String[][]

**Comment by wumpz** [comment]
Since each cell should be treated like a word isn't that identical to merging all cells to a line and comparing a list of those?

**Comment by wise-coders** [comment]
Maybe it would work, but the code would be much cleaner and better if would exists a method to compare tables directly.
Isn't it possible to add a such a method to java-diff-utils?

**Comment by wumpz** [comment]
Could you make a suggestion?

**Comment by wise-coders** [comment]
If possible, please implement a method to compare a table as list of arrays List<String[]> and return the matching, added, changed and dropped rows. The compare should focus only at the row level.

**Comment by wumpz** [comment]
Since diffing is a text processing algorithm, I will not implement this. Since you are diffing each cell against each cell you should call the differ for each cell and display this result. However, connecting cells to rows will not work, since the idff algorithm would not preserve cell position for patching.
