### ISSUE TITLE
Feature Request - To Merge Differences

### ISSUE THREAD

**Issue by gvjoshi25** [java-diff-utils/java-diff-utils#168]
**Describe the Feature**
A new request to consider including whitespace (space in my case) to represent the differences.

**To Reproduce**
1. Example data --> Included in snippet.
2. simple program snippet
```
import java.util.Arrays;
import java.util.List;

import com.github.difflib.text.DiffRow;
import com.github.difflib.text.DiffRowGenerator;

public class ShowDiffViewUsingJavaDiffUtils {

    static String leftString = "A sample string to test this tool.";
    static String rightString = "A sample string is defined here and will be used to test diff library.";

    public static void main(String[] args) throws Throwable {

      //create a configured DiffRowGenerator
        DiffRowGenerator generator = DiffRowGenerator.create()
                        .ignoreWhiteSpaces(true)
                        .showInlineDiffs(true)
                        .mergeOriginalRevised(false)
                        .inlineDiffByWord(true)
                        .oldTag(f -> "--")
                        .newTag(f -> "++")
                        .build();

        //compute the differences for two test texts.
        List<DiffRow> rows = generator.generateDiffRows(
                        Arrays.asList(leftString),
                        Arrays.asList(rightString));
        
        rows.stream().forEach(r -> {
            System.out.println("OldLine: " + r.getOldLine());
            System.out.println("NewLine: " + r.getNewLine());
        });

    }

}

```
3. See error - NA.

**Expected behavior**
The output of my program is:
```
OldLine: A sample string to test --this-- --tool--.
NewLine: A sample string ++is defined here and will be used ++to test ++diff++ ++library++.
```

I would like to have this diff tool to consider whitespace. e.g. consider whitespace between `this tool` for the differences.
Expected output:
```
OldLine: A sample string to test --this tool--.
NewLine: A sample string ++is defined here and will be used ++to test ++diff library++.
```

I have tried all possible configurations to achieve this, but no luck, hence raising this request. If the feature does exist, please share the details.

**System**
 - Java version - 1.8
 - Version - 4.12

**Comment by epictecch** [comment]
I have the same requirement and did not find a way to configure the `DiffRowGenerator` accordingly.
### Solution proposal
In my opinion, the best choice from the library point of view would be to allow users to merge the inline deltas when processing them in `DiffRowGenerator.generateInlineDiffs()`. In accordance with the other existing configuration options, we could introduce an `inlineDeltaMerger` property. In order to not break compatibility, the `DEFAULT_INLINE_DELTA_MERGER` would not do anything. A `WHITESPACE_INLINE_DELTA_MERGER` would eliminate all deltas with `DeltaType.CHANGE` that consists of whitespace only. The whitespace would be moved to the adjacent deltas.

Would you accept such a PR or does this somehow violate existing concepts of the library?
