### ISSUE TITLE
How to get the original line number?

### ISSUE THREAD

**Issue by kivihub** [java-diff-utils/java-diff-utils#39]
### Expected Behavior
The class DiffRow may add field to record the original line number.

### Actual Behavior
no method to get the line number.

### Steps to Reproduce the Problem
none

### Specifications

  - Version: 4.0
  - Platform: Ubuntu 18
  - Subsystem:

**Comment by wumpz** [comment]
Line numbers are within the Patch class.
-------- Ursprüngliche Nachricht --------Von: kivihub <notifications@github.com> Datum: 29.04.19  08:21  (GMT+01:00) An: java-diff-utils/java-diff-utils <java-diff-utils@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [java-diff-utils/java-diff-utils] How to get the original line
  number? (#39) Expected Behavior
The class DiffRow may add field to record the original line number.
Actual Behavior
no method to get the line number.
Steps to Reproduce the Problem
none
Specifications

Version: 4.0
Platform: Ubuntu 18
Subsystem:


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/java-diff-utils/java-diff-utils","title":"java-diff-utils/java-diff-utils","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/java-diff-utils/java-diff-utils"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"How to get the original line number? (#39)"}],"action":{"name":"View Issue","url":"https://github.com/java-diff-utils/java-diff-utils/issues/39"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/java-diff-utils/java-diff-utils/issues/39",
"url": "https://github.com/java-diff-utils/java-diff-utils/issues/39",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kivihub** [comment]
> Line numbers are within the Patch class. -------- Ursprüngliche Nachricht --------Von: kivihub <notifications@github.com> Datum: 29.04.19 08:21 (GMT+01:00) An: java-diff-utils/java-diff-utils <java-diff-utils@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [java-diff-utils/java-diff-utils] How to get the original line   number? (#39) Expected Behavior The class DiffRow may add field to record the original line number. Actual Behavior no method to get the line number. Steps to Reproduce the Problem none Specifications Version: 4.0 Platform: Ubuntu 18 Subsystem: —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread. {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/java-diff-utils/java-diff-utils","title":"java-diff-utils/java-diff-utils","subtitle":"GitHub repository","main_image_url":"[https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open](https://github.githubassets.com/images/email/message_cards/header.png%22,%22avatar_image_url%22:%22https://github.githubassets.com/images/email/message_cards/avatar.png%22,%22action%22:%7B%22name%22:%22Open) in GitHub","url":"[https://github.com/java-diff-utils/java-diff-utils"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"How](https://github.com/java-diff-utils/java-diff-utils%22%7D%7D,%22updates%22:%7B%22snippets%22:%5B%7B%22icon%22:%22DESCRIPTION%22,%22message%22:%22How) to get the original line number? (#39)"}],"action":{"name":"View Issue","url":"#39"}}} [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#39", "url": "#39", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Thank you for reply, I'll try it.
