### ISSUE TITLE
[Feature request] Consider making project modular

### ISSUE THREAD

**Issue by dector** [java-diff-utils/java-diff-utils#55]
It's nice to have zero-dependency implementations. I think it's possible to split library into 2 or modules:

```
diff-utils-core
diff-utils-myers
diff-utils-jgit
```

or (just moving `jgit` dependency out of core library):
```
diff-utils
diff-utils-jgit
```

**Comment by dector** [comment]
Can do this if `gradle` PR will be accepted. :)

**Comment by wumpz** [comment]
My simple solution was to make the jgit dependency optional. So This should be no hurdle. But you are right, that a separate module would make it cleaner.

**Comment by dector** [comment]
Yeah, separate Maven module might be a nice solution.

**Comment by wumpz** [comment]
My problem is, I would have to make another change request to sonatype. The new module should be published to maven central as well. Is this indeed worth the whole 
effort? I don't think so. At least at the moment.

**Comment by JakeWharton** [comment]
Sonatype grants access per groupId. You don't have to do anything provided the three artifacts are published under the same groupId. Once you have access, you can publish as many artifacts as you want beneath it.

**Comment by wumpz** [comment]
Are you positive about this? I thought it was done by group I'd and artefact ID.Tobias
-------- Ursprüngliche Nachricht --------Von: Jake Wharton <notifications@github.com> Datum: 01.11.19  02:40  (GMT+01:00) An: java-diff-utils/java-diff-utils <java-diff-utils@noreply.github.com> Cc: Tobias <t.warneke@gmx.net>, Comment <comment@noreply.github.com> Betreff: Re: [java-diff-utils/java-diff-utils] [Feature request] Consider
  making project modular (#55) Sonatype grants access per groupId. You don't have to do anything provided the three artifacts are published under the same groupId. Once you have access, you can publish as many artifacts as you want beneath it.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/java-diff-utils/java-diff-utils/issues/55?email_source=notifications\u0026email_token=AAL7EOLWRFPNJ7JIOEDZ7HDQROCHBA5CNFSM4JCQNLG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECZXT6Q#issuecomment-548633082",
"url": "https://github.com/java-diff-utils/java-diff-utils/issues/55?email_source=notifications\u0026email_token=AAL7EOLWRFPNJ7JIOEDZ7HDQROCHBA5CNFSM4JCQNLG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECZXT6Q#issuecomment-548633082",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JakeWharton** [comment]
Yep, I'm sure!

**Comment by wumpz** [comment]
Could you check the latest multi-module branch. Are you still positive, that sonatype will accept this if I do a release?

**Comment by JakeWharton** [comment]
It looks good to me from a quick glance at the poms. I'm positive they'll accept it. You can test by deploying a snapshot to Sonatype from the branch. The same permissions are applied to the snapshot repository as the staging repository for release.

**Comment by wumpz** [comment]
I staged the first multi-module version at sonatype. There were no errors within my pom.xml after some editing. So wait and see, if this whole bunch is published to maven central. By the way, it should be version 4.4.

**Comment by wumpz** [comment]
I think it was published successfully.

**Comment by JakeWharton** [comment]
Thanks! Looks good on search.maven.org. I'll test in my project later today.

**Comment by JakeWharton** [comment]
And working great!

**Comment by wumpz** [comment]
Super.
