### ISSUE TITLE
javadoc: document when DiffException is thrown

### ISSUE THREAD

**Issue by cdalexndr** [java-diff-utils/java-diff-utils#70]
Please add javadoc explaining why **DiffException** is thrown.

What's the reason that diff-ing two strings may throw **DiffException** (`DiffUtils.diffInline`)?
Shouldn't string diff never throw an exception?

**Comment by wumpz** [comment]
Ha. Good question. I will look into it.

**Comment by wumpz** [comment]
After digging into it this, I realized that this was by design of the original library I think.
The diff algorithm could throw something by this for any unexpected behaviour. But I think this should be an unchecked exception. So the algorithm could throw some illegal state or so. 

I will remove this exception.

**Comment by wumpz** [comment]
Done in version 4.7-SNAPSHOT.

**Comment by cowwoc** [comment]
@wumpz Can you cut a new release with this change?
