### ISSUE TITLE
columnWidth seems to be causing br tags to be inserted in the class name

### ISSUE THREAD

**Issue by disccomp** [java-diff-utils/java-diff-utils#81]
**Describe the bug**
Using the default tags, columnWidth seems to be causing br tags to be inserted in the class name.

**To Reproduce**
original:
> American bobtail jaguar. American bobtail bombay but turkish angora and tomcat. 
> Russian blue leopard. Lion. Tabby scottish fold for russian blue, so savannah yet lynx. Tomcat singapura, cheetah. 
> Bengal tiger panther but singapura but bombay munchkin for cougar.

revised:
> bobtail jaguar. American bobtail turkish angora and tomcat. 
> Russian blue leopard. Lion. Tabby scottish folded for russian blue, so savannah yettie? lynx. Tomcat singapura, cheetah. 
> Bengal tiger panther but singapura but bombay munchkin for cougar. And more.

2. simple programm snippet:
```
g = DiffRowGenerator.create().showInlineDiffs(true).ignoreWhiteSpaces(true).columnWidth(100).build();
deltas = g.generateDiffRows([original],[revised]);

ArrayEach(deltas,function(delta){
  writeOutput(delta.getOldLine());
  writeOutput(" | ");
  writeOutput(delta.getNewLine());
});
```

**See error**
```html
<span class="editOldInline">American </span>bobtail jaguar. American bobtail <span class="editOldInl<br/>ine">bombay bu</span>t<span class="editOldInline"> t</span>urkish angora and tomcat.  | bobtail jaguar. American bobtail turkish angora and tomcat. 

Russian blue leopard. Lion. Tabby scottish fold for russian blue, so savannah yet lynx. Tomcat singa<br/>pura, cheetah.  | Russian blue leopard. Lion. Tabby scottish fold<span class="editNewInline">ed</span> for russian blu<br/>e, so savannah yet<span class="editNewInline">tie?</span> lynx. Tomcat singapura, cheetah. 

Bengal tiger panther but singapura but bombay munchkin for cougar. | Bengal tiger panther but singapura but bombay munchkin for cougar.<span class="editNewInline"> And m<br/>ore.</span>
```
**Expected behavior**
2nd span class should not contain a &lt;br&gt; tag
```<span class="editOldInl```&lt;br/&gt;```ine">```

**Comment by wumpz** [comment]
This is right. For the diff utils you are comparing text. That there are "tags" with different sematics this tool does not know. Therefore the diff could be within the tags and so the linefeeds could be.

**Comment by disccomp** [comment]
This is comparing plaintext. Those span tags are being added by this tool.

**Comment by wumpz** [comment]
Oops. My failure. 
-------- Ursprüngliche Nachricht --------Von: Mark Moran <notifications@github.com> Datum: 05.06.20  15:07  (GMT+01:00) An: java-diff-utils/java-diff-utils <java-diff-utils@noreply.github.com> Cc: Tobias <t.warneke@gmx.net>, Comment <comment@noreply.github.com> Betreff: Re: [java-diff-utils/java-diff-utils] columnWidth seems to be causing
  br tags to be inserted in the class name (#81) 
This is comparing plaintext. Those span tags are being added by this tool.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/java-diff-utils/java-diff-utils/issues/81#issuecomment-639468471",
"url": "https://github.com/java-diff-utils/java-diff-utils/issues/81#issuecomment-639468471",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wumpz** [comment]
I looked into it and to be honest I don't know how to solve this in a good way. For this inline method the columnwith should be skipped.
